### ISSUE TITLE
Only able to apply colour to 1 word / sentence

### ISSUE THREAD

**Issue by royhermans** [mendixlabs/rich-text#4]
Hi,

I can select some text and mark that text with a colour, for example yellow like on the screenshot below.
![screenshot_80](https://user-images.githubusercontent.com/32068390/30547211-f3ed2d96-9c8e-11e7-9f16-aeb493855e0f.png)

![screenshot_81](https://user-images.githubusercontent.com/32068390/30547212-f3f36d64-9c8e-11e7-924b-1ae34e408f87.png)

After that when I select another piece of text the colour on the first one will disappear as soon as I click on the colour select button (see screenshots above and below).
![screenshot_82](https://user-images.githubusercontent.com/32068390/30547214-f40a5a10-9c8e-11e7-8271-52119e0c57aa.png)

**Comment by edwinmp** [comment]
Hi @royhermans, finding trouble replicating this issues. See the attached GIF. Could you please replicated this in a simple test project and send me the mpk.
![richtextcolorpicker](https://user-images.githubusercontent.com/5672438/30635199-5c26155a-9dfa-11e7-908e-d402c50d427e.gif)

**Comment by royhermans** [comment]
Hi @edwinmp , it took me a little while to be able to replicate the issue myself in a test project but I managed to do it. I have zipped the mpk file.
[RichText_Test.zip](https://github.com/mendixlabs/rich-text/files/1336574/RichText_Test.zip)

**Comment by royhermans** [comment]
[RichText_Test_2.zip](https://github.com/mendixlabs/rich-text/files/1336586/RichText_Test_2.zip)

The problem seems to be caused by the sanize string action. In our project (and the testproject as well) we use use an OC save mf which also sanitizes the string.
 In this testproject I removed the java action from the MF so I get the exact same string out as I put in and then the problem doesn't happen.

**Comment by edwinmp** [comment]
Hi @royhermans, thanks for the reproduction. It led me to another bug partly responsible for the above behaviour. To adhere to the existing behavior of the Mendix input widgets, the onChange microflow is only triggered on blur (if a change was made). Unfortunately, clicking on the editor toolbar was being taken as a blur event & would cause the editor to lose focus.

This shall be fixed in the next release.

As to what's happening in your projects, the only solution is as you've realised ... removing the sanitize action.

**Comment by edwinmp** [comment]
The selection issue has been fixed in version [1.0.2](https://github.com/mendixlabs/rich-text/releases/tag/1.0.2).
